---
title: "St. Olaf WBB 2022-23 MIAC Game Report"
author: "St. Olaf Sports Analytics Club"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gt)
library(DT)
library(tidyverse)
source("Lineup_Cleaning.R")
source("PBP_Cleaning.R")
```



```{r, echo = FALSE}
miac_lineups %>%
  count(opp, date) %>% 
  select(date, opp, -n) %>%
  arrange(date) %>%
  rename(Date = date,
         Opponent = opp) %>%
  gt() %>%
  tab_header(title = "MIAC Games Included in this Report")
```


#### [Link to All Games Statistics](https://matous1.github.io/STO_WBB_2022_23/Game_Report.html) 




```{r, include = F}
lu1.0 <- miac_lineups %>% # THIS IS THE ONLY LINE DIFFERENT FROM Game_Report.Rmd
  separate(Time, into = c("min", "sec"), sep = ":") %>%
  mutate(min = parse_number(min),
         sec = parse_number(sec),
         total_mins = ((min*60) + sec)/60,
         Hegland = str_detect(Lineup, "Hegland"),
         Olmen = str_detect(Lineup, "Olmen"),
         Fix = str_detect(Lineup, "Fix"),
         Kelly = str_detect(Lineup, "Kelly"),
         Howdeshell = str_detect(Lineup, "Howdeshell"),
         Yagodinski = str_detect(Lineup, "Yagodinski"),
         Johnson = str_detect(Lineup, "Johnson"),
         Tangen = str_detect(Lineup, "Tangen"),
         Kormann = str_detect(Lineup, "Kormann"),
         Botten = str_detect(Lineup, "Botten"),
         Zhen = str_detect(Lineup, "Zhen"))

players = c("Hegland", "Olmen", "Fix", "Kelly", "Howdeshell", "Yagodinski", "Johnson", "Tangen", "Kormann", "Botten", "Zhen")
```


# **Individual Summary Statistics - MIAC Games**

```{r, include = FALSE}
individual_summary <- function(player) {
  lu1.0 %>%
  filter(eval(rlang::data_sym({{player}})) == TRUE) %>%
  mutate(pts_allowed = Score - Score_Diff) %>%
  summarise(mins = sum(total_mins),
            pts_per_min = sum(Score) / mins,
            pts_allowed_per_min = sum(pts_allowed) / mins,
            pt_dif = pts_per_min - pts_allowed_per_min,
            reb_per_min = sum(Reb) / mins,
            stl_per_min = sum(Stl) / mins,
            tov_per_min = sum(Tov) / mins,
            ast_per_min = sum(Ast) / mins) %>%
  add_column(player = player)
}

lu1.0 %>%
  filter(eval(rlang::data_sym("Hegland")) == TRUE)

tmp <- tibble()


for (i in players) {
  tmp_row <- individual_summary(i)  
  tmp <- bind_rows(tmp, tmp_row)
}

ind_sum_stats <- tmp %>%
  select(player, 1:8) %>% 
  arrange(-mins)
  
```

```{r, echo = FALSE}
ind_sum_stats %>%
  filter(mins > 2) %>%
  arrange(-pt_dif) %>%
  gt() %>%
  fmt_number(columns = c(where(is.numeric)), decimals = 2) %>%
  data_color(
    columns = c(pt_dif),
    colors = scales::col_numeric(
      palette = c("red", "green"),
      domain = c(-1, 1),
      ), alpha = 0.8
  ) %>%
  tab_header(
    title = md("**Individual Player Summaries STO WBB 22-23**"),
    subtitle = paste0("Through ", max(lineups$date))
)
```

# **Lineup Reports - MIAC Games** {.tabset .tabset-fade .tabset-pills}


```{r, include = FALSE}
lu_names <- c("Players",
              "Min", 
              "Pts/Min", 
              "Pts Allowed/Min", 
              "Point Diff", 
              "Reb/Min",
              "Stl/Min",
              "TOV/Min",
              "Ast/Min")

num_games <- 2
```




## 2 Person Lineups {.tabset .tabset-fade .tabset-pills}

```{r, echo = FALSE}
two_plyr_summary_test <- function(df, player1, player2) {
  player1_col <- sym(player1)
  player2_col <- sym(player2)
  df %>%
  filter({{player1_col}} == TRUE, {{player2_col}} == TRUE)%>%
  mutate(pts_allowed = Score - Score_Diff) %>%
  summarise(mins = sum(total_mins),
            pts_per_min = sum(Score) / mins,
            pts_allowed_per_min = sum(pts_allowed) / mins,
            pt_dif = pts_per_min - pts_allowed_per_min,
            reb_per_min = sum(Reb) / mins,
            stl_per_min = sum(Stl) / mins,
            tov_per_min = sum(Tov) / mins,
            ast_per_min = sum(Ast) / mins)%>%
    mutate(player1 = player1,
           player2 = player2) %>%
    select(player1, player2, where(is.numeric))
}

two_person_lineups <- tibble()

for(i in 1:length(players)){
  for(j in 1:length(players)){
    if(i < j){
      hold<- two_plyr_summary_test(lu1.0, players[i], players[j])
      two_person_lineups <- bind_rows(two_person_lineups, hold)
    }
  }
}


two_person_lineups <- two_person_lineups %>%
  mutate(players = str_c(player1, player2, sep = ", ")) %>%
  select(players, -(player1:player2), where(is.numeric)) %>%
  arrange(-mins) %>%
  filter(mins > 2*num_games) %>%
  mutate_if(is.numeric, round, digits = 2)
  

# datatable(batters20, filter = 'top', options = list(
#   pageLength = 20,
#   legnthMenu = c(5, 10, 20, 50, 100)
# ))

datatable(two_person_lineups, 
          class = 'display order-column',
          filter = 'top', 
          colnames = lu_names,
          options = list(
  pageLength = 20,
  lengthMenu = c(5, 10, 20, 40),
  autoWidth = T
))
  
  # colnames(two_person_lineups) <- lu_names2


# two_person_lineups %>%
#   gt() %>%
#   fmt_number(columns = c(where(is.numeric)), decimals = 2) %>%
#   data_color(
#     columns = c(`Point Diff`),
#     colors = scales::col_numeric(
#       palette = c("red", "green"),
#       domain = c(-2, 2),
#       ), alpha = 0.8
#   ) %>%
#   tab_header(
#     title = md("**2 Player Lineup Summaries STO WBB 22-23**"),
#     subtitle = paste0("Through ", max(pbp$date)))
  
  #All 36 two_person lineups voila

```


## 3 Person Lineups {.tabset .tabset-fade .tabset-pills}

```{r, echo = FALSE}
three_plyr_summary_test <- function(df, player1, player2, player3) {
  player1_col <- sym(player1)
  player2_col <- sym(player2)
  player3_col <- sym(player3)
  df %>%
  filter({{player1_col}} == TRUE, {{player2_col}} == TRUE, {{player3_col}} == TRUE)%>%
  mutate(pts_allowed = Score - Score_Diff) %>%
  summarise(mins = sum(total_mins),
            pts_per_min = sum(Score) / mins,
            pts_allowed_per_min = sum(pts_allowed) / mins,
            pt_dif = pts_per_min - pts_allowed_per_min,
            reb_per_min = sum(Reb) / mins,
            stl_per_min = sum(Stl) / mins,
            tov_per_min = sum(Tov) / mins,
            ast_per_min = sum(Ast) / mins)%>%
    mutate(player1 = player1,
           player2 = player2,
           player3 = player3) %>%
    select(player1:player3, 1:8)
}

# three_plyr_summary_test(lu1.0, "Kelly", "Fix", "Olmen")%>%
#   print(width = Inf)

#Basic Template for 3 person lineups without all code
# for(i in 1:5){
#   for(j in 1:5){
#     if(i < j){
#     for (k in 1:5){
#       if(j<k){
#       print(paste0(i, j, k))
#       }
#     }
#     }
#   }
# }

#3 person
three_person_lineups <- tibble()

for(i in 1:length(players)){
  for(j in 1:length(players)){
    if(i<j){
    for (k in 1:length(players)){
      if(j<k){
        hold<- three_plyr_summary_test(lu1.0, players[i], players[j], players[k])
        three_person_lineups <- bind_rows(three_person_lineups, hold)    
        }
      }
    }
  }
}

three_person_lineups <- three_person_lineups %>%
  mutate(players = str_c(player1, player2, player3, sep = ", ")) %>%
  select(players, -(player1:player3), where(is.numeric)) %>%
  arrange(-mins) %>%
  filter(mins > 3*num_games) %>%
  mutate_if(is.numeric, round, digits = 2) 

datatable(three_person_lineups, 
          filter = 'top', 
          colnames = lu_names,
          class = 'display order-column',
          options = list(
  pageLength = 20,
  lengthMenu = c(5, 10, 20, 40),
  autoWidth = T
))


# three_person_lineups %>%
#   gt() %>%
#   fmt_number(columns = c(where(is.numeric)), decimals = 2) %>%
#   data_color(
#     columns = c(`Point Diff`),
#     colors = scales::col_numeric(
#       palette = c("red", "green"),
#       domain = c(-2, 2),
#       ), alpha = 0.8
#   ) %>%
#   tab_header(
#     title = md("**3 Player Lineup Summaries STO WBB 22-23**"),
#     subtitle = paste0("Through ", max(pbp$date)))


#### Trial code to not to do lineup options with a bunch of for loops - unsuccessful for now
# expand.grid(players, players, players)
# 
# combos <- as_tibble(expand.grid(players, players, players))%>%
#   filter(as.character(Var1) != as.character(Var2),
#          as.character(Var1)<as.character(Var2)) %>% 
#   mutate(Var1 = as.character(Var1),
#          Var2 = as.character(Var2))
# 
# 
# combos[1,]
# 
# 
# 
# two_plyr_summary_test(lu1.0, combos$Var1[1], combos$Var2[1])
# 
# two_plyr_summary_test(lu1.0, as.character(combos$Var1[1]), as.character(combos$Var2[1]))
```

## 4 Person Lineups {.tabset .tabset-fade .tabset-pills}

```{r, echo = FALSE}
four_plyr_summary_test <- function(df, player1, player2, player3, player4) {
  player1_col <- sym(player1)
  player2_col <- sym(player2)
  player3_col <- sym(player3)
  player4_col <- sym(player4)
  df %>%
  filter({{player1_col}} == TRUE, {{player2_col}} == TRUE, {{player3_col}} == TRUE, {{player4_col}} == TRUE) %>%
  mutate(pts_allowed = Score - Score_Diff) %>%
  summarise(mins = sum(total_mins),
            pts_per_min = sum(Score) / mins,
            pts_allowed_per_min = sum(pts_allowed) / mins,
            pt_dif = pts_per_min - pts_allowed_per_min,
            reb_per_min = sum(Reb) / mins,
            stl_per_min = sum(Stl) / mins,
            tov_per_min = sum(Tov) / mins,
            ast_per_min = sum(Ast) / mins) %>%
    mutate(player1 = player1,
           player2 = player2,
           player3 = player3,
           player4 = player4) %>%
    select(player1:player4, 1:8)
}

# four_plyr_summary_test(lu1.0, "Kelly", "Fix", "Olmen", "Hegland")%>%
#   print(width = Inf)

four_person_lineups <- tibble()

for(i in 1:length(players)){
  for(j in 1:length(players)){
    if(i < j){
    for (k in 1:length(players)){
      if(j < k) {
      for (l in 1:length(players)){
          if(k < l) {
            hold <- four_plyr_summary_test(lu1.0, players[i], players[j], players[k], players[l])
            four_person_lineups <- bind_rows(four_person_lineups, hold)  
          }
        }
        }
      }
    }
  }
}


four_person_lineups <- four_person_lineups %>%
  mutate(players = str_c(player1, player2, player3, player4, sep = ", ")) %>%
  select(players, -(player1:player4), where(is.numeric)) %>%
  arrange(-mins) %>%
  filter(mins > 2*num_games) %>%
  mutate_if(is.numeric, round, digits = 2) 

datatable(four_person_lineups, 
          filter = 'top', 
          colnames = lu_names,
          class = 'display order-column',
          options = list(
  pageLength = 20,
  lengthMenu = c(5, 10, 20, 40),
  autoWidth = T
))




# 
# four_person_lineups %>%
#   gt() %>%
#   fmt_number(columns = c(where(is.numeric)), decimals = 2) %>%
#   data_color(
#     columns = c(`Point Diff`),
#     colors = scales::col_numeric(
#       palette = c("red", "green"),
#       domain = c(-2, 2),
#       ), alpha = 0.8
#   ) %>%
#   tab_header(
#     title = md("**4 Player Lineup Summaries STO WBB 22-23**"),
#     subtitle = paste0("Through ", max(pbp$date)))


```


## 5 Person Lineups {.tabset .tabset-fade .tabset-pills}

```{r, echo = FALSE}
five_plyr_summary_test <- function(df, player1, player2, player3, player4, player5) {
  player1_col <- sym(player1)
  player2_col <- sym(player2)
  player3_col <- sym(player3)
  player4_col <- sym(player4)
  player5_col <- sym(player5)
  df %>%
  filter({{player1_col}} == TRUE, {{player2_col}} == TRUE, {{player3_col}} == TRUE, {{player4_col}} == TRUE, {{player5_col}} == TRUE) %>%
  mutate(pts_allowed = Score - Score_Diff) %>%
  summarise(mins = sum(total_mins),
            pts_per_min = sum(Score) / mins,
            pts_allowed_per_min = sum(pts_allowed) / mins,
            pt_dif = pts_per_min - pts_allowed_per_min,
            reb_per_min = sum(Reb) / mins,
            stl_per_min = sum(Stl) / mins,
            tov_per_min = sum(Tov) / mins,
            ast_per_min = sum(Ast) / mins) %>%
    mutate(player1 = player1,
           player2 = player2,
           player3 = player3,
           player4 = player4,
           player5 = player5) %>%
    select(player1:player5, 1:8)
}

five_person_lineups <- tibble()

for(i in 1:length(players)){
  for(j in 1:length(players)){
    if(i < j){
    for (k in 1:length(players)){
      if(j < k) {
      for (l in 1:length(players)){
          if(k < l) {
          for (x in 1:length(players)){
            if(l < x) {
            hold <- five_plyr_summary_test(lu1.0, players[i], players[j], players[k], players[l], players[x])
            five_person_lineups <- bind_rows(five_person_lineups, hold)  
            }
          }
        }
        }
      }
    }
  }
  }
}


five_person_lineups <- five_person_lineups %>%
  mutate(players = str_c(player1, player2, player3, player4, player5, sep = ", ")) %>%
  select(players, -(player1:player5), where(is.numeric)) %>%
  arrange(-mins) %>%
  filter(mins > num_games) %>%
  mutate_if(is.numeric, round, digits = 2) 


datatable(five_person_lineups, 
          filter = 'top', 
          colnames = lu_names,
          class = 'display order-column',
          options = list(
  pageLength = 20,
  lengthMenu = c(5, 10, 20, 40),
  autoWidth = T
))



# five_person_lineups %>%
#   gt() %>%
#   fmt_number(columns = c(where(is.numeric)), decimals = 2) %>%
#   data_color(
#     columns = c(`Point Diff`),
#     colors = scales::col_numeric(
#       palette = c("red", "green"),
#       domain = c(-2, 2),
#       ), alpha = 0.8
#   ) %>%
#   tab_header(
#     title = md("**5 Player Lineup Summaries STO WBB 22-23**"),
#     subtitle = paste0("Through ", max(pbp$date)))



```

