---
title: "WBB Lineup Analysis"
output: html_document
date: '2022-12-07'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(dplyr)
library(nlme)
library(mosaic)
library(base)
library(lubridate)

source("Lineup_Cleaning.R")

lineups <- lineups %>%
  separate(Time, into = c("min", "sec"), sep = ":") %>%
  mutate(min = parse_number(min),
         sec = parse_number(sec),
         game_time = ((min*60) + sec)/60)
```

```{r, messing around}
lineups %>%
  filter(str_detect(Lineup, "Kelly R")) %>%
  summarise(total_mins = sum(game_time),
            point_diff = sum(Score_Diff)/total_mins,
            ppm = sum(Pts_Min, na.rm = TRUE)/total_mins,
            ppp = sum(PPP)/total_mins
            )

lineups %>%
  filter(str_detect(Lineup, "Howdeshell S")) %>%
  summarise(total_mins = sum(game_time),
            point_diff = sum(Score_Diff)/nrow(lineups),
            ppm = sum(Pts_Min, na.rm = TRUE)/nrow(lineups),
            ppp = sum(PPP)/nrow(lineups)
            )

analyze <- function(player){
  lineups %>%
    mutate(points_allowed = Score - Score_Diff) %>%
    filter(str_detect(Lineup, player)) %>%
    summarise(total_mins = sum(game_time),
            ppm = sum(Score, na.rm = TRUE)/total_mins,
            ppp = sum(PPP)/total_mins,
            papm = sum(points_allowed)/total_mins,
            point_diff = sum(Score_Diff)/total_mins
            )
}

analyze("Botten")
analyze("Fix")
analyze("Hegland")
analyze("Howdeshell")
analyze("Johnson")
analyze("Kelly")
analyze("Kormann")
analyze("Olmen")
analyze("Tangen")
analyze("Yagodinski")
analyze("Zhen")
```

```{r}
lineups %>%
  summarise(minutes = sum(game_time))
```

