---
title: "WBB PBP Analysis"
output: html_document
date: '2022-12-07'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(dplyr)
library(nlme)
library(mosaic)
library(base)
library(lubridate)
library(stringr)

source("PBP_Cleaning.R")

pbp_full <- pbp

pbp <-pbp %>%
  filter(team == "STO")

pbp2 <- pbp

```

```{r}
#points scored on a possession minus the average points per possession for each game (summed per player)
#players with a positive number lead to high value possessions when they shoot
#players with a negative number lead to low value possessions when they shoot
pbp %>%
  group_by(date) %>%
  filter(action == "GOOD" | action == "MISS") %>%
  mutate(points_scored = ifelse(action == "GOOD" & type == "LAYUP", 2, 0),
         points_scored = ifelse(action == "GOOD" & type == "JUMPER", 2, points_scored),
         points_scored = ifelse(action == "GOOD" & type == "3PTR", 3, points_scored),
         points_scored = ifelse(action == "GOOD" & type == "LAYUP", 2, points_scored),
         points_scored = ifelse(action == "GOOD" & type == "FT", 1, points_scored),
         possession = 1,
         total_game_points = sum(points_scored),
         total_game_possessions = sum(possession),
         exp_pos_pts = total_game_points/total_game_possessions,
         pts_over_exp = points_scored - exp_pos_pts) %>%
  ungroup() %>%
  group_by(checkname52) %>%
  summarise(total_points_added = sum(pts_over_exp),
            points_added_per = total_points_added/n()) %>%
  arrange(-points_added_per)

#same table as above, but by quarter
quarter_max <- pbp %>%
  group_by(date) %>%
  filter(action == "GOOD" | action == "MISS") %>%
  mutate(points_scored = ifelse(action == "GOOD" & type == "LAYUP", 2, 0),
         points_scored = ifelse(action == "GOOD" & type == "JUMPER", 2, points_scored),
         points_scored = ifelse(action == "GOOD" & type == "3PTR", 3, points_scored),
         points_scored = ifelse(action == "GOOD" & type == "LAYUP", 2, points_scored),
         points_scored = ifelse(action == "GOOD" & type == "FT", 1, points_scored),
         possession = 1,
         total_game_points = sum(points_scored),
         total_game_possessions = sum(possession),
         exp_pos_pts = total_game_points/total_game_possessions,
         pts_over_exp = points_scored - exp_pos_pts) %>%
  ungroup() %>%
  group_by(checkname52, quarter) %>%
  summarise(points_added = sum(pts_over_exp)) %>%
  arrange(quarter, -points_added)
```

```{r, assist to turnover}
pbp %>%
  filter(checkname52 != "TEAM") %>%
  filter(action == "ASSIST" | action == "TURNOVER") %>%
  group_by(checkname52) %>%
  summarise(assists = sum(action == "ASSIST"),
            turnovers = sum(action == "TURNOVER"),
            `a/t` = assists/turnovers) %>%
  arrange(-`a/t`)

#pbp %>%
  #filter(action == "TURNOVER" | action == "ASSIST") %>%
  
```

```{r, shooting pct by quarter}
shooting_by_quarter <- pbp %>%
  filter(checkname52 != "TEAM") %>%
  filter(type != "FT") %>%
  group_by(checkname52, quarter) %>%
  mutate(points = ifelse(action == "GOOD" & type == "LAYUP", 2, 0),
         points = ifelse(action == "GOOD" & type == "JUMPER", 2, points),
         points = ifelse(action == "GOOD" & type == "3PTR", 3, points),
         points = ifelse(action == "GOOD" & type == "LAYUP", 2, points),
         points = ifelse(action == "GOOD" & type == "FT", 1, points)) %>%
  summarise(total_points = sum(points),
            shots = sum(action == "GOOD") + sum(action == "MISS"),
            shooting_pct = sum(action == "GOOD")/
              (sum(action == "GOOD") + sum(action == "MISS")),
            shooting_pct = ifelse(is.na(shooting_pct), 0, shooting_pct))


ggplot(data = shooting_by_quarter,
       aes(x = quarter,
           y = shooting_pct,
           color = fct_reorder2(checkname52, quarter, shooting_pct))) +
  geom_point() +
  #geom_line() +
  geom_smooth(se = FALSE) +
  labs(title = "Shooting Percentage by Quarter",
       y = "shooting percentage",
       color = "player") +
  theme_classic()

shooting_by_quarter <- shooting_by_quarter %>%
  mutate(checkname52 = tolower(checkname52))

#filter out players with low volume to make it neater
shooting_by_quarter2 <- shooting_by_quarter %>%
  filter(checkname52 != "johnson,kylie", checkname52 != "howdeshell,sarah", checkname52 != "kormann,sophia", checkname52 != "zhen,ziling")

ggplot(data = shooting_by_quarter2,
       aes(x = quarter,
           y = shooting_pct,
           color = fct_reorder2(checkname52, quarter, shooting_pct))) +
  geom_point() +
  #geom_line() +
  geom_smooth(se = FALSE) +
  labs(title = "Shooting Percentage by Quarter",
       y = "shooting percentage",
       color = "player") +
  theme_classic()

#just starters
shooting_by_quarter3 <- shooting_by_quarter2 %>%
  filter(checkname52 != "tangen,sarah", checkname52 != "botten,cayden")

#just starters
ggplot(data = shooting_by_quarter3,
       aes(x = quarter,
           y = shooting_pct,
           color = fct_reorder2(checkname52, quarter, shooting_pct))) +
  geom_point() +
  #geom_line() +
  geom_smooth(se = FALSE) +
  labs(title = "Shooting Percentage by Quarter",
       y = "shooting percentage",
       color = "player") +
  theme_classic()

quarterly_shooting <- function(player){
  shooting_by_quarter %>%
    filter(str_detect(checkname52, {{player}})) %>%
    ggplot(aes(x = quarter, y = shooting_pct)) +
    geom_point() +
    geom_smooth(color = "#CB831A") +
    labs(title = str_c(str_to_title({{player}}), " Shooting by Quarter"),
         y = "shooting percentage") +
    theme_classic()
}

quarterly_shooting("botten")
quarterly_shooting("fix")
quarterly_shooting("hegland")
quarterly_shooting("kelly")
quarterly_shooting("olmen")
quarterly_shooting("tangen")
quarterly_shooting("yagodinski")

#strong first quarter shooters: hegland, kelly
#strong second quarter shooters: hegland, olmen
#strong third quarter shooters: fix, hegland, kelly, olmen, tangen
#strong fourth quarter shooters: botten, hegland, tangen, yagodinski

```

```{r}
#points per shot (excluding free throws)
pbp %>%
  filter(checkname52 != "TEAM") %>%
  filter(type != "FT") %>%
  group_by(checkname52) %>%
  mutate(points = ifelse(action == "GOOD" & type == "LAYUP", 2, 0),
         points = ifelse(action == "GOOD" & type == "JUMPER", 2, points),
         points = ifelse(action == "GOOD" & type == "3PTR", 3, points),
         points = ifelse(action == "GOOD" & type == "LAYUP", 2, points)) %>%
  summarise(total_points = sum(points),
            shots = sum(action == "GOOD") + sum(action == "MISS"),
            pts_per_shot = total_points/shots) %>%
  arrange(-pts_per_shot)

#shot distribution by player
pbp %>%
  filter(checkname52 != "TEAM") %>%
  filter(action == "GOOD" | action == "MISS") %>%
  group_by(checkname52) %>%
  summarise(layups = sum(type == "LAYUP"),
            mid_range = sum(type == "JUMPER"),
            threes = sum (type == "3PTR")
            ) 

pbp %>%
  filter(checkname52 != "TEAM") %>%
  filter(action == "GOOD" | action == "MISS") %>%
  group_by(checkname52) %>%
  summarise(layups = sum(type == "LAYUP"),
            layup_pct = sum(action == "GOOD" & type == "LAYUP")/
              sum(type == "LAYUP")
            ) %>%
  filter(layups > 5) %>%
  arrange(-layup_pct)

pbp %>%
  filter(checkname52 != "TEAM") %>%
  filter(action == "GOOD" | action == "MISS") %>%
  group_by(checkname52) %>%
  summarise(mid_range = sum(type == "JUMPER"),
            mid_pct = sum(action == "GOOD" & type == "JUMPER")/
              sum(type == "JUMPER")
            ) %>%
  filter(mid_range > 5) %>%
  arrange(-mid_pct)

pbp %>%
  filter(checkname52 != "TEAM") %>%
  filter(action == "GOOD" | action == "MISS") %>%
  group_by(checkname52) %>%
  summarise(threes = sum (type == "3PTR"),
            three_pct = sum(action == "GOOD" & type == "3PTR")/
              sum(type == "3PTR")
            ) %>%
  filter(threes > 5) %>%
  arrange(-three_pct)

pbp %>%
  group_by(checkname52) %>%
  filter(action == "GOOD" | action == "MISS") %>%
  summarise(fts = sum(type == "FT"),
            ft_pct = sum(action == "GOOD" & type == "FT")/
              sum(type == "FT")
            ) %>%
  filter(fts > 5) %>%
  arrange(-ft_pct)
```

```{r, true shooting percentage}
pbp %>%
  filter(action == "GOOD" | action == "MISS") %>%
  mutate(points = ifelse(action == "GOOD" & type == "LAYUP", 2, 0),
         points = ifelse(action == "GOOD" & type == "JUMPER", 2, points),
         points = ifelse(action == "GOOD" & type == "3PTR", 3, points),
         points = ifelse(action == "GOOD" & type == "LAYUP", 2, points),
         points = ifelse(action == "GOOD" & type == "FT", 1, points))%>%
  group_by(checkname52) %>%
  summarise(`TS%` = 100*sum(points)/
              (2*(sum(type == "LAYUP" | type == "JUMPER" | type == "3PTR") +
                    0.44*sum(type == "FT")
                  )
                                   )
            ) %>%
  arrange(-`TS%`)
```

```{r, usage rate}
usage <- function(player){
  lineups %>%
    mutate(Lineup = tolower(Lineup)) %>%
    mutate(total_mins = sum(game_time)) %>%
    filter(str_detect(Lineup, {{player}})) %>%
    full_join(pbp) %>%
    mutate(checkname52 = tolower(checkname52)) %>%
    summarise(usage_rate = sum(100 * (sum(action == "MISS" | action == "GOOD" & type != "FT" & str_detect(checkname52, {{player}})) + 0.44 * sum(type == "FT" & str_detect(checkname52, {{player}})) + sum(action == "TURNOVER" & str_detect(checkname52, {{player}}))
                                  ) * (total_mins/5) /
                sum(game_time) * (sum(action == "MISS" | action == "GOOD" & type != "FT") + 0.44 * sum(type == "FT") + sum(type == "TURNOVER"))
              )
    )
}

usage("kelly")

lineups %>%
  filter(str_detect(Lineup, "Botten")) %>%
    summarise(total_mins = sum(game_time))

lineups %>%
    summarise(total_mins = sum(game_time))

```

```{r, rebound rate}
rebounding <- function(player){
  lineups %>%
    mutate(Lineup = tolower(Lineup)) %>%
    mutate(total_mins = sum(game_time)) %>%
    filter(str_detect(Lineup, {{player}})) %>%
    left_join(pbp2) %>%
    mutate(checkname52 = tolower(checkname52)) %>%
    summarise(rebound_rate = 100 * (sum(action == "REBOUND" & str_detect(checkname52, {{player}})) * (total_mins/5))
              /(sum(game_time)*sum(action == "REBOUND"))
              ) %>%
    head(1)
}

rebounding("botten")
rebounding("fix")
rebounding("hegland")
rebounding("kelly")
rebounding("kormann")
rebounding("olmen")
rebounding("yagodinski")
```

```{r, per}

```

```{r}
pbp %>%
  filter(action == "STEAL" | action == "BLOCK" | action == "FOUL") %>%
  group_by(checkname52) %>%
  summarise(steals = sum(action == "STEAL"),
            blocks = sum(action == "BLOCK"),
            fouls = sum(action == "FOUL"),
            contests = n(),
            foul_rate = fouls/contests) %>%
  arrange(foul_rate)
```

```{r}
#proportions of players rebounds that are offensive rebounds
pbp %>%
  filter(action == "REBOUND") %>%
  filter(checkname52 != "TEAM") %>%
  group_by(checkname52) %>%
  summarise(offensive = sum(type == "OFF"),
            defensive = sum(type == "DEF"),
            total = n(),
            off_reb_rate = offensive/total) %>%
  arrange(-off_reb_rate)

pbp_full %>%
  filter(action == "REBOUND") %>%
  group_by(date) %>%
  summarise(sto_off = sum(team == "STO" & type == "OFF"),
            sto_def = sum(team == "STO" & type == "DEF"),
            opp_off = sum(team != "STO" & type == "OFF"),
            opp_def = sum(team != "STO" & type == "DEF"),
            orb_pct = sto_off/(sto_off + opp_def),
            drb_pct = sto_def/(sto_def + opp_off)) %>%
  add_column(result = c(1,1,1,0,0,0,0))
#games where rebounding is higher generally corellate strongly with wins
```

```{r}
game_shooting <- pbp %>%
  filter(checkname52 != "TEAM") %>%
  filter(action == "GOOD" | action == "MISS") %>%
  group_by(date) %>%
  summarise(layups = sum(type == "LAYUP"),
            mid_range = sum(type == "JUMPER"),
            threes = sum (type == "3PTR"),
            layup_pct = sum(action == "GOOD" & type == "LAYUP") / layups,
            mid_pct = sum(action == "GOOD" & type == "JUMPER") / mid_range,
            three_pct = sum(action == "GOOD" & type == "3PTR") / threes
            )

game_shooting

game_shooting %>%
  ggplot(aes(x = date, y = three_pct)) +
  geom_point() +
  geom_line(color = "#CB831A") +
  theme_classic()
#three pointers have recently gotten significantly better

game_shooting %>%
  ggplot(aes(x = date, y = mid_pct)) +
  geom_point() +
  geom_line(color = "#CB831A") +
  theme_classic()
#mid range shots have been relatively consistent outside of the 11/19 game

game_shooting %>%
  ggplot(aes(x = date, y = layup_pct)) +
  geom_point() +
  geom_line(color = "#CB831A") +
  theme_classic()
```

